language: node_js
node_js:
    - "node"

sudo: required

services:
    - docker

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
    - cd BackEnd
    - docker run -v "`pwd`:/home/builder/" tracesoftware/gitlab-builder:php7-cli /bin/sh -c "mkdir -p $ARCHIVE_PATH $DOCS_PATH; chmod -R 777 $DATA_PATH; composer update; composer test"
    - cd ../FrontEnd
    - yarn
    - yarn test
    - yarn build:prod
    - cd ..

after_success:
  - docker login  -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
  - docker build -t tracesoftware/hostmydocs .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tracesoftware/hostmydoc:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u="$DOCKER_USERNAME"" -p="$DOCKER_PASSWORD";
    docker push tracesoftware/hostmydoc:dev;
    fi
